version: '3.8'
services:
  mysql:
    image: mysql:8
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER=${DB_USER:-kologermit}
      - MYSQL_PASSWORD=${DB_PASSWORD:-Qwerty5432}
      - MYSQL_DATABASE=${DB_NAME:-schedule86}
      - MYSQL_ROOT_PASSWORD=${DB_ROOT_PASSWORD:-Qwerty5432}
    ports:
      - ${DB_EXTERNAL_PORT:-5000}:3306
    volumes:
      - ./db:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
#      - ./mysql/low-memory-my.cnf:/etc/mysql/my.cnf:ro
    networks:
      - mysql
#    mem_limit: "600M"
      
  telebot:
    build: ./bot
    restart: on-failure
    volumes:
      - "./bot:/code"
    networks:
      - mysql
    depends_on:
      - mysql
    mem_limit: "60M"

networks:
  mysql:
    driver: bridge
