version: '3.8'
services:
  mysql:
    image: mysql:8.0
    cap_add:
      - SYS_NICE
    restart: always
    environment:
      - MYSQL_USER='kologermit'
      - MYSQL_PASSWORD='Qwerty5432'
      - MYSQL_DATABASE=schedule86
      - MYSQL_ROOT_PASSWORD=Qwerty5432
    ports:
      - '5000:3306'
    volumes:
      - ./db:/var/lib/mysql
      - ./db-init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - mysql
    mem_limit: "600M"
      
  telebot:
    build: ./bot
    restart: on-failure
    volumes:
      - "./bot:/code"
    networks:
      - mysql
    depends_on:
      - mysql
    mem_limit: "60M"

networks:
  mysql:
    driver: bridge
